### ISSUE TITLE
Allow semaphore to acquire more than one token/lock/resource per call 

### ISSUE THREAD

**Issue by Sytten** [swarthy/redis-semaphore#18]
Hi there!
Currently the semaphore `acquire` methods doesn't accept any parameter. This means that if a user requires more than one token/lock/resource, he needs to call the method twice (thus make two calls to redis). It would be valuable if we could only pass it an integer and be done with it.
An example of this use case is an application making calls to an external system with a limit on the concurrent connections (say 4). If I need to make 2 concurrent connections or none to this service, I want to be able to acquire 2 tokens/locks from the semaphore or error out.
Thanks a lot!

**Comment by swarthy** [comment]
Hi!
Adding int argument to ```acquire``` is not quite correct, because there are several ways how to make multiple lock. For your example, lets say there are 5 running instances of application which should connect to service (some of them needs 1 lock to open single connection, other needs 2). Instance1 locks two slots, Instance2 locks one slot, after that there are one free slot left. What should instance3 do? Waits until two slots become available (possibly may never happend, cause there are instance2 which can always lock "third" slot)? Or should it lock one slot and waits until other one will be released. If second UX is what you want, then you can do it with current interface: create two instances of ```Semaphore``` with same key and call ```await Promise.all([semaphore1.acquire(), semaphore2.acquire()])```, which is more clear I guess.
For that UX it's better to create something like "MultiSemaphore" class with ```acquire``` which will internally create multiple ```Semaphore```s and call ```acquire``` for each of them, I guess. What do you think? Thanks

**Comment by Sytten** [comment]
So i believe that `instance3` here should throw on the acquire if it requires 2 but only 1 slot is available. That really depends if you hold locks for a long time or if it is a temporary lock. I think that should be left to the application developer.
A `MultiSemaphore` class could work, but I would expect it to be atomic and in the case of using multiple classes of `Semaphore` under it, it won't be. 
I feel this script https://github.com/swarthy/redis-semaphore/blob/master/src/semaphore/acquire/lua.ts#L14-L18
could be adapted to to do something like (not a lua programmer, so probably wrong but you get the gist):
```lua
if redis.call('zcard', key) + ask <= limit then
    array = {}
    for i= 0, ask do
        array[i*2] = now
        array[i+1] = identifier
    end
    redis.call('zadd', key, unpack(array))
```
Thanks!

**Comment by swarthy** [comment]
```MultiSemaphore``` was added in v3.2.0

**Comment by Sytten** [comment]
Wow so fast, thank you so much, this is awesome!
