### ISSUE TITLE
Support for ioredis-mock

### ISSUE THREAD

**Issue by germanescobar** [swarthy/redis-semaphore#201]
Hi,

I have a case in which I need to pass an [ioredis-mock](https://www.npmjs.com/package/ioredis-mock) instance for testing but I get the following error:

```
"client" must be instance of ioredis client or cluster
```

Is there a solution or workaround for this case?

Thanks!

**Comment by jokester** [comment]
If maintainers thinks it's fine I'm happy to do something. I personally wanted a mutex that work with Upstash serverless redis.

The idea on my head is, to extract a ioredis-like `interface` and rely on the interface instead of `instanceof` check. Since only a few Redis APIs are required, I imagine the interface to be small. Other redis clients, even if they happen to name APIs differently, can be used with an adapter.

**Comment by swarthy** [comment]
@jokester Hi! PR is welcome

**Comment by swarthy** [comment]
Support for `ioredis-mock` added in v5.6.0
