### ISSUE TITLE
Lost mutex when computer comes out of standby mode

### ISSUE THREAD

**Issue by eric-vinci** [swarthy/redis-semaphore#24]
Hello,

I am using mutex to synchronize mutiple apollo servers (10 Docker images on a single computer) and everything works as expected when the computer is up and running. Only one apollo server instance is doing the job at a time.
But when the computer awakes after being in sleep mode, then things go wrong.

1) I get the following error messages even with try/catch everywhere : 
apollo_7    | (node:55) UnhandledPromiseRejectionWarning: Error: Lost mutex for key mutex:LogsCleanerMutex
apollo_7    |     at RedisMutex._processRefresh (/usr/src/app/node_modules/redis-semaphore/src/Lock.ts:85:15)
apollo_7    |     at processTicksAndRejections (internal/process/task_queues.js:97:5)
apollo_7    | (node:55) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)

2) Multiple apollo server instances are doing the same job.

Versions in use :
 - "redis-semaphore": "^4.0.1"
 - redis:alpine (Docker image)
 - apollo:latest with node:erbium (Docker image)

Please can you help ?

**Comment by swarthy** [comment]
Hi!
After some time (more than ```acquireTimeout```) in sleep mode, record in Redis expires and after awake Redis deletes it (lock belongs to noone now).
When your node service awakes, it tries to refresh the previously acquired lock and can't make it, because lock doesn't belongs to this service anymore (and throws unhandling rejection by design, cause "hmm, I got the lock some time ago, refreshing it and now it doesn't belongs to me. wtf?!").
I guess there is no best solution here. You can disable refresh behaviour by passing ```refreshInterval: 0``` and set a big enough ```acquireTimeout``` value so that your service has time to process job.

**Comment by leszekhanusz** [comment]
Our problem is that the critical code for our needs is actually never ending.

It is something like:

```javascript
while(true) {
  // sleep 10 seconds
  // calculate some stats
}
```

And we want to release the mutex only if this instance is stopped or crashes.

As you explained, with the current design of redis-semaphore, there is no way to warn the user code that there was a problem to refresh the previously acquired mutex.

So this is in fact a feature request, we would like to have a way to be warned that we lost the mutex unexpectedly.

There are multiple ways to do that, we could either provide a callback to redis-semaphore which is called when this happens or the mutex returned by redis-semaphore could be an event emitter so that we could do something like:

```javascript
const mutex = new Mutex(redisClient, 'lockingResource')
still_have_mutex = true;

mutex.on('lock_lost', () => {
  still_have_mutex = false;
})

await mutex.acquire()
try {
  while (still_have_mutex) {
    // our loop
  }
} finally {
  await mutex.release()
}
```

**Comment by swarthy** [comment]
Added ```.isAcquired``` and ```onLockLost``` in v4.1.0, so you can do something like
```typescript
const mutex = new Mutex(redisClient, 'lockingResource', { onLockLost(err) { console.error(err) } })
await mutex.acquire()
try {
  while (mutex.isAcquired) {
    // our loop
  }
} finally {
  await mutex.release()
}
```

**Comment by leszekhanusz** [comment]
Thank you!
